# Generated by Django 3.2 on 2021-04-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationTool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='setup_type',
            field=models.CharField(default='NA', max_length=125),
            preserve_default=False,
        ),
    ]
